### ISSUE TITLE
decision table with multiple actions, and Any for return type, needs missing ContextImpl

### ISSUE THREAD

**Issue by dbutler** [goldmansachs/jdmn#533]
### Expected Behavior
we attempted to define a decision table with multiple actions, and a return type of Any/Context.
this mimics functionality we need in our real tables in our project that generates DMN with Visual Studio Code 1.67.1

we expect that this is allowed as it appears to be valid DMN and is valid to the redhat runtime we are using
		<dependency>
			<groupId>org.kie</groupId>
			<artifactId>kie-dmn-core</artifactId>
			<version>${drools.version}</version>
		</dependency>
		<dependency>
			<groupId>org.kie</groupId>
			<artifactId>kie-dmn-validation</artifactId>
			<version>${drools.version}</version>
		</dependency>
		<dependency>
			<groupId>org.kie</groupId>
			<artifactId>kie-dmn-api</artifactId>
			<version>${drools.version}</version>
		</dependency>
...
		<drools.version>7.58.0.Final</drools.version>

### Actual Behavior
we see a compile time error

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project dmn-demo-kjar-v1: Compilation failure: Compilation failure: 
[ERROR] /Users/dbutler/projects/eclipse-workspace/dmn-demo-jdmn-v2/target/generated-sources/dmn/com/foo/AgeClassification.java:[196,27] cannot find symbol
[ERROR]   symbol:   class ContextImpl
[ERROR]   location: package com.gs.dmn.runtime
[ERROR] /Users/dbutler/projects/eclipse-workspace/dmn-demo-jdmn-v2/target/generated-sources/dmn/com/foo/AgeClassification.java:[196,72] cannot find symbol
[ERROR]   symbol:   class ContextImpl
[ERROR]   location: package com.gs.dmn.runtime
[ERROR] -> [Help 1]

### jDMN Version where this issue was observed

5.5.2

### Steps to reproduce the behavior
mvn clean generate-sources install

attached a sample project showing the issue

[dmn-demo-jdmn-v2.tar.gz](https://github.com/goldmansachs/jdmn/files/8679054/dmn-demo-jdmn-v2.tar.gz)

**Comment by opatrascoiu** [comment]
The issue is  cause by imprecise modelling. jDMN was designed such that data types are modelled using concrete types (e.g. FEEL types and ItemDefinitons). The idea is to catch as many semantic errors as possible at compile time. Using Any (similar with Object in Java) as a type creates this kind of problems. Other DMN engines are not that strict, increasing the number of errors reported at runtime.
Once you model the output of Age Classification as above, the issue should be solved.
I'll add some error messages in the next release to make the error more obvious.
